#!/usr/bin/env python3

import csv, time
from collections import defaultdict

def read_csv(csvfile, inputstr):
    file_name = csvfile
    transitions = []
    with open(file_name, mode ='r')as file:
        csvFile = csv.reader(file)
        for line, lines in enumerate(csvFile):
            #first line grab name of machine
            if line == 0:
                name = lines
            elif line == 4:
                start = lines
            elif line == 5:
                accept = lines
            elif line == 6:
                reject = lines
            elif line >= 7:
                transitions.append(lines)
        info = [start, accept, reject, inputstr]
        transitions_dict = transdict(transitions)
        configurations = bfs(transitions, transitions_dict, info)

    for config in configurations:
        print(config)
            
def transdict(transitions):
    transitions_dict = defaultdict(list)
    for transition in transitions:
        transitions_dict[transition[0]].append(transition)
    return dict(transitions_dict)

def bfs(transitions, transitions_dict, info):
    #variables
    notfound = True
    level = 0
    curr_state = ''.join(info[0])
    accept_state = ''.join(info[1])
    reject_state = ''.join(info[2])
    ogstr = ''.join(info[3])

    #configuration stuff
    configurations = [[["", curr_state, ogstr]]]            # initial configuration
    
    #if the string is empty check for any transitions else reject
    if not ogstr:
        ogstr = "_"
    #     for transition in transitions:
    #         print(transition)
    #         # check the state in transitions dict and if the input matches a transition
    #         # if find a transition, do it
    #         if (curr_state in transitions_dict) and (ogstr == transitions_dict[curr_state][1]):
    #             add_config = go_right("", ogstr, transition)
    #             configurations.append(add_config)
    #         # if transition match is not found, go into a reject state
    #         else:
    #             add_config = go_right("", ogstr, transition, reject_state=reject_state, rej=True)
    #             configurations.append(add_config)
    #     return configurations                    
    while notfound:
        level_configs = []                                  # configurations for current level

        # look at each configuration at the current
        for config in configurations[level]:
            leftstr = config[0]
            rightstr = config[2]
            curr_state = config[1]
            check_char = rightstr[0] if rightstr else '_'

            print(f'right string: {rightstr}')

            if curr_state == reject_state:
                continue

            #check transitions for the current state
            if curr_state in transitions_dict:
                    for trans in transitions_dict[curr_state]:
                        if trans[1] == check_char:
                            if trans[-1] == 'R':
                                add_config = go_right(leftstr, rightstr, trans)
                            elif trans[-1] == 'L':
                                add_config = go_left(leftstr, rightstr, trans)
                            level_configs.append(add_config)
                        else:
                            add_config = go_right(leftstr, rightstr, trans, reject_state, rej=True)
                            level_configs.append(add_config)

        if level_configs:
            convert_tup = {tuple(config) for config in level_configs}
            convert_list = [list(config) for config in convert_tup]
            configurations.append(convert_list)

        for config in configurations[level]:
            if accept_state in config:
                notfound = False
                break

        level += 1

    return configurations

def go_left(leftstr, rightstr, trans):
    # if the left string is empty make it into a blank
    if len(leftstr) == 0:
        leftstr += '_'

    # newleft is leftstr without last character and newright is rightstr with new written character on front
    newleft = leftstr[:-1]
    newright = trans[3] + rightstr

    #new configuration
    return [newleft, trans[2], newright]

def go_right(leftstr, rightstr, trans, reject_state=None, rej=False):
    # if the right string needs a character to read in
    if len(rightstr) <= 1:
        rightstr += '_'

    #newright is rightstr without old head
    newright = rightstr[1:]

    #check to see if it goes to reject state or not and returns new configuration
    if rej:
        #if does go to reject state, newleft is leftstr with head of rightstr and new state is reject state
        newleft = leftstr + rightstr[0]
        return [newleft, reject_state, newright]
    else:
        #if does not go to a reject state, newleft is left str with rewrite character added and the state transition specified
        newleft = leftstr + trans[3]
        return [newleft, trans[2], newright]

def main():
    inputstr = ""
    read_csv("abc_star.csv", inputstr)

if __name__ == "__main__":
    main()